services:
  postgres:
    image: postgres:latest
    container_name: postgres-database
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: postgres
      POSTGRES_DB: go-dev-database
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - go-server-network
    restart: always

volumes:
  pgdata:

networks:
  go-server-network:
    external: true
