services:
  postgres:
    image: postgres:latest
    container_name: postgres-database
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: postgres
      POSTGRES_DB: go-dev-database
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data  # Persist data using a Docker volume
    networks:
      - go-server-network
    restart: always  # Optional: Automatically restart the container if it fails or is stopped

volumes:
  pgdata:  # Define a volume named 'pgdata' for persistent storage

networks:
  go-server-network:
    external: true
